# This workflow does the following:
#  - Builds the Java project with Maven
#  - Converts TODO comments to GitHub issues

name: Main Workflow

on:
  push:
    paths:
    - 'src/**'
    - 'pom.xml'
  pull_request:
    paths:
    - 'src/**'
    - 'pom.xml'
    
  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:
    
jobs:
  
  # Builds Java project with Maven
  build-maven:
    runs-on: windows-latest
    
    # Only run this job on main branch
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
          
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
        architecture: x64
        
    # Cache Maven ~/.m2 directory so we don't need to download
    # dependencies every build
    - name: Cache Maven Packages
      uses: actions/cache@v2.1.4
      with:
        path: C:\Users\runneradmin\.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

     # Output runner Maven cache, used for debugging
#    - name: Output Maven packages
#      run: |
#        echo "outputting dir of C:\Users\runneradmin\.m2\repository"
#        echo ""
#        cd "C:\Users\runneradmin\.m2\repository"
#        dir
#        echo "outputting dir of C:\Users\runneradmin\.m2\repository\org"
#        cd org
#        dir
    
    # Finally build Java project with Maven    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  # Converts '// TODO' comments to GitHub issues when a new commit is pushed
  todo-to-issue:
    # Only runs on ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.6.5
        id: todo
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "TODO"
          COMMENT_MARKER: "//"
          CLOSE_ISSUES: "true"


