# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows this workflow to be run manually from the Actions tab
  workflow_dispatch:
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

#    - name: Check for up-to-date Maven cache
#      uses: actions/cache@v2
#      id: maven-cache
#      with:
#        path: ~/.m2/repository
#        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#        restore-keys: |
#          ${{ runner.os }}-maven-
          
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
        architecture: x64
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Output settings
      run: |
        echo "outputting dir of C:\Users\runneradmin\.m2\repository"
        echo ""
        cd "C:\Users\runneradmin\.m2\repository"
        dir
        echo "outputting dir of C:\Users\runneradmin\.m2\repository\org"
        cd org
        dir
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
        

    
    # Cache local Maven repository when pom.xml changes
    #- name: Cache local Maven repository if needed
      
      
